version: '3.8'

services:
  coinquest:
    build:
      context: .
      args:
        - GIT_AUTH_TOKEN=${GIT_AUTH_TOKEN}
    image: taggara/coinquest:latest
    container_name: coinquest
    ports:
      - "${PORT:-8099}:8099"
    volumes:
      - ${APPDATA_PATH:-/mnt/user/appdata/coinquest}:/app
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
      - GIT_AUTH_TOKEN=${GIT_AUTH_TOKEN}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8099}
    command: >
      sh -c "git clone https://oauth2:${GIT_AUTH_TOKEN}@github.com/taggara/coinquest.git /app &&  # Updated path here
            npm install &&  # Ensure this runs in the correct directory
            npm run build:web &&  # Ensure this runs in the correct directory
            serve -s web-build -l ${PORT:-8099} -H ${HOST:-0.0.0.0}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST:-0.0.0.0}:${PORT:-8099}/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    restart: unless-stopped