version: '3.8'

services:
  coinquest:
    build: .
    container_name: coinquest
    ports:
      - "8099:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    restart: unless-stopped