version: '3.8'

services:
  coinquest:
    build: 
      context: .
      args:
        - GIT_AUTH_TOKEN=${GIT_AUTH_TOKEN}
    container_name: coinquest
    ports:
      - "8099:8099"
    volumes:
      - /mnt/user/appdata/coinquest:/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - GIT_AUTH_TOKEN=${GIT_AUTH_TOKEN}
      - HOST=192.168.4.52
      - PORT=8099
    command: >
      sh -c "git clone https://oauth2:${GIT_AUTH_TOKEN}@github.com/taggara/coinquest.git /mnt/user/appdata/coinquest && 
            npm install && 
            npm run build:web && 
            serve -s web-build -l 8099 -H 192.168.4.52"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.4.52:8099/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    restart: unless-stopped