version: '3.8'

services:
  coinquest:
    build:
      context: .
      args:
        - GIT_AUTH_TOKEN=${GIT_AUTH_TOKEN}
    image: taggara/coinquest:latest
    container_name: coinquest
    ports:
      - "${PORT:-8089}:8089"
    volumes:
      - /mnt/user/appdata/coinquest:/app/appdata
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=sqlite:///app/appdata/data/local.db
      - GIT_AUTH_TOKEN=${GIT_AUTH_TOKEN}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8089}
      - PUID=99
      - PGID=100
    command: >
      sh -c "git clone https://oauth2:${GIT_AUTH_TOKEN}@github.com/taggara/coinquest.git /app/appdata &&  # Updated path here
            cd /app/appdata &&  # Ensure commands run in the correct directory
            npm install &&
            npm run build:web &&
            serve -s web-build -l ${PORT:-8089} -H ${HOST:-0.0.0.0}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST:-0.0.0.0}:${PORT:-8089}/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    restart: unless-stopped
